# Generated by Django 4.2.3 on 2023-07-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChessPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "piece_type",
                    models.CharField(
                        choices=[
                            ("Queen", "Queen"),
                            ("Bishop", "Bishop"),
                            ("Rook", "Rook"),
                            ("Knight", "Knight"),
                        ],
                        max_length=10,
                    ),
                ),
                ("position", models.CharField(max_length=2)),
            ],
        ),
    ]
