# Generated by Django 4.2.3 on 2023-07-25 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chess_moves", "0002_remove_chesspiece_piece_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chesspiece",
            name="user",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
